# Generated by Django 5.1.4 on 2025-07-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_category', models.CharField(max_length=100)),
                ('iocs', models.TextField(verbose_name='IOCs (Indicators of Compromise)')),
                ('threat_actor', models.CharField(max_length=200)),
                ('attack_vector', models.CharField(max_length=200)),
                ('geo_location', models.CharField(max_length=100)),
                ('forum_sentiment', models.CharField(max_length=50)),
                ('severity_score', models.IntegerField()),
                ('predicted_category', models.CharField(max_length=100)),
                ('suggested_defense', models.TextField()),
                ('risk_level', models.CharField(max_length=50)),
                ('cleaned_description', models.TextField()),
                ('keywords', models.TextField()),
                ('named_entities', models.TextField()),
                ('topic_labels', models.TextField()),
                ('word_count', models.IntegerField()),
            ],
        ),
    ]
